package publish;

import enums.ActivityState;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import logic.DataTypeActivity;
import logic.DataTypeInscription;
import logic.DataTypeOuting;
import logic.DataTypeProvider;
import logic.DataTypeTourist;
import logic.DataTypeUser;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "WebServices", targetNamespace = "http://publish.altoViaje/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServices {
	
	/**
     * 
     * @return
     *     returns DataTypeUser[]
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publish.altoViaje/WebServices/listUsersRequest", output = "http://publish.altoViaje/WebServices/listUsersResponse")
    public DataTypeUser[] listUsers();
	
    /**
     * 
     * @return
     *     returns DataTypeTourist[]
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publish.altoViaje/WebServices/listTouristsRequest", output = "http://publish.altoViaje/WebServices/listTouristsResponse")
    public DataTypeTourist[] listTourists();
    
    /**
     * 
     * @return
     *     returns DataTypeProvider[]
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publish.altoViaje/WebServices/listProvidersRequest", output = "http://publish.altoViaje/WebServices/listProvidersResponse")
    public DataTypeProvider[] listProviders();
    
    /**
     * 
     * @param nickname
     * @return
     *     returns DataTypeUser
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publish.altoViaje/WebServices/dataUserRequest", output = "http://publish.altoViaje/WebServices/dataUserResponse")
    public DataTypeUser dataUser(
    		@WebParam(name = "nickname", partName = "nickname") String arg0
    		);

    /**
     * 
     * @return
     *     returns DataTypeOuting[]
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publish.altoViaje/WebServices/listTouristOutingsRequest", output = "http://publish.altoViaje/WebServices/listTouristOutingsResponse")
    public DataTypeOuting[] listTouristOutings();
    
    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns DataTypeActivity[]
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publish.altoViaje/WebServices/listProviderActivitiesRequest", output = "http://publish.altoViaje/WebServices/listProviderActivitiesResponse")
    public DataTypeActivity[] listProviderActivities(
        @WebParam(name = "arg0", partName = "arg0") String arg0,
        @WebParam(name = "arg1", partName = "arg1") Boolean arg1
        );
    
    /**
     * 
     * @param arg0
     * @return
     *     returns DataTypeInscription[]
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publish.altoViaje/WebServices/getTouristInscriptionsRequest", output = "http://publish.altoViaje/WebServices/getTouristInscriptionsResponse")
    public DataTypeInscription[] getTouristInscriptions(
        @WebParam(name = "arg0", partName = "arg0") String arg0
        );
    
    /**
     * 
     * @param arg0
     * @return
     *     returns void
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publish.altoViaje/WebServices/addTouristRequest", output = "http://publish.altoViaje/WebServices/addTouristResponse")
    public void addTourist(
        @WebParam(name = "arg0", partName = "arg0") DataTypeTourist arg0
        );
    
    /**
     * 
     * @param arg0
     * @return
     *     returns void
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publish.altoViaje/WebServices/addProviderRequest", output = "http://publish.altoViaje/WebServices/addProviderResponse")
    public void addProvider(
        @WebParam(name = "arg0", partName = "arg0") DataTypeProvider arg0
        );
    
    
    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns DataTypeActivity
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publish.altoViaje/WebServices/getCurrentProviderNicknameRequest", output = "http://publish.altoViaje/WebServices/getCurrentProviderNicknameResponse")
    public DataTypeActivity addInscription(
        @WebParam(name = "arg0", partName = "arg0") String arg0,
        @WebParam(name = "arg1", partName = "arg1") String arg1
        );
    
    /**
     * 
     * @param arg0
     * @return
     *     returns DataTypeActivity[]
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publish.altoViaje/WebServices/listTouristActivitiesRequest", output = "http://publish.altoViaje/WebServices/listTouristActivitiesResponse")
    public DataTypeActivityArray listTouristActivities(
    		@WebParam(name = "arg0", partName = "arg0") ActivityState arg0
    		);
    
    /**
     * 
     * @param arg0
     * @return
     *     returns DataTypeActivity[]
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publish.altoViaje/WebServices/listTouristActivitiesRequest", output = "http://publish.altoViaje/WebServices/listTouristActivitiesResponse")
    public DataTypeActivityArray boolListTouristActivities(
    		@WebParam(name = "arg0", partName = "arg0") boolean arg0
    		);
    
    /**
     * 
     * @param arg0
     * @return
     *     returns DataTypeOuting[]
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publish.altoViaje/WebServices/chooseActivityRequest", output = "http://publish.altoViaje/chooseActivityResponse")
    public DataTypeOutingArray chooseActivity(
    		@WebParam(name = "arg0", partName = "arg0") String arg0
    		);
    
    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns void
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publish.altoViaje/WebServices/activityRegistrationRequest", output = "http://publish.altoViaje/WebServices/activityRegistrationResponse")
    public void activityRegistration(
    		@WebParam(name = "arg0", partName = "arg0") String arg0,
    		@WebParam(name = "arg1", partName = "arg1") DataTypeActivity arg1
    		);
    
    /**
     * 
     * @param arg0
     * @return
     *     returns void
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publish.altoViaje/WebServices/confirmActivityRequest", output = "http://publish.altoViaje/WebServices/confirmActivityResponse")
    public void confirmActivity(
    		@WebParam(name = "arg0", partName = "arg0") String arg0
    		);
   
    /**
     * 
     * @param arg0
     * @return
     *     returns void
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publish.altoViaje/WebServices/rejectActivityRequest", output = "http://publish.altoViaje/WebServices/rejectActivityResponse")
    public void rejectActivity(
    		@WebParam(name = "arg0", partName = "arg0") String arg0
    		);
}